ROUTINE_LIST_MESSAGE = "Routine lookup was successful."
ROUTINE_LIST_STATUS = "ROUTINE_LIST_OK"

ROUTINE_CREATE_MESSAGE = "You have successfully created the routine."
ROUTINE_CREATE_STATUS = "ROUTINE_CREATE_OK"

ROUTINE_DETAIL_MESSAGE = "Routine lookup was successful."
ROUTINE_DETAIL_STATUS = "ROUTINE_DETAIL_OK"

ROUTINE_UPDATE_MESSAGE = "The routine has been modified."
ROUTINE_UPDATE_STATUS = "ROUTINE_UPDATE_OK"

ROUTINE_DELETE_MESSAGE = "The routine has been deleted."
ROUTINE_DELETE_STATUS = "ROUTINE_DELETE_OK"

ROUTINE_RESULT_UPDATE_MESSAGE = "The routine's result has been updated."
ROUTINE_RESULT_UPDATE_STATUS = "ROUTINE_RESULT_UPDATE_OK"
